CREATE VIEW infovip AS SELECT
  vip.prenom as Prénom,
  vip.nom as Nom,
  CONCAT(UCASE(LEFT(type.nom, 1)),SUBSTRING(type.nom, 2)) as Type,
  CONCAT(UCASE(LEFT(pays.nom, 1)),SUBSTRING(pays.nom, 2)) as Nationalite,
  vip.importance as Importance
  FROM vip inner join type on vip.id_type=type.id INNER JOIN pays on vip.id_pays=pays.id;




INSERT INTO vip values ('1','Vin','Diesel')


/*Création de la table Pays */


  INSERT INTO `pays` (`id`, `nom`) values ('AF', 'Afghanistan');
  INSERT INTO `pays` (`id`, `nom`) values ('ZA', 'Afrique du Sud');
  INSERT INTO `pays` (`id`, `nom`) values ('AL', 'Albanie');
  INSERT INTO `pays` (`id`, `nom`) values ('DZ', 'Algérie');
  INSERT INTO `pays` (`id`, `nom`) values ('DE', 'Allemagne');
  INSERT INTO `pays` (`id`, `nom`) values ('AD', 'Andorre');
  INSERT INTO `pays` (`id`, `nom`) values ('AO', 'Angola');
  INSERT INTO `pays` (`id`, `nom`) values ('AI', 'Anguilla');
  INSERT INTO `pays` (`id`, `nom`) values ('AQ', 'Antarctique');
  INSERT INTO `pays` (`id`, `nom`) values ('AG', 'Antigua-et-Barbuda');
  INSERT INTO `pays` (`id`, `nom`) values ('SA', 'Arabie saoudite');
  INSERT INTO `pays` (`id`, `nom`) values ('AR', 'Argentine');
  INSERT INTO `pays` (`id`, `nom`) values ('AM', 'Arménie');
  INSERT INTO `pays` (`id`, `nom`) values ('AW', 'Aruba');
  INSERT INTO `pays` (`id`, `nom`) values ('AU', 'Australie');
  INSERT INTO `pays` (`id`, `nom`) values ('AT', 'Autriche');
  INSERT INTO `pays` (`id`, `nom`) values ('AZ', 'Azerbaïdjan');
  INSERT INTO `pays` (`id`, `nom`) values ('BS', 'Bahamas');
  INSERT INTO `pays` (`id`, `nom`) values ('BH', 'Bahreïn');
  INSERT INTO `pays` (`id`, `nom`) values ('BD', 'Bangladesh');
  INSERT INTO `pays` (`id`, `nom`) values ('BB', 'Barbade');
  INSERT INTO `pays` (`id`, `nom`) values ('BE', 'Belgique');
  INSERT INTO `pays` (`id`, `nom`) values ('BZ', 'Belize');
  INSERT INTO `pays` (`id`, `nom`) values ('BJ', 'Bénin');
  INSERT INTO `pays` (`id`, `nom`) values ('BM', 'Bermudes');
  INSERT INTO `pays` (`id`, `nom`) values ('BT', 'Bhoutan');
  INSERT INTO `pays` (`id`, `nom`) values ('BY', 'Biélorussie');
  INSERT INTO `pays` (`id`, `nom`) values ('BO', 'Bolivie');
  INSERT INTO `pays` (`id`, `nom`) values ('BA', 'Bosnie-Herzégovine');
  INSERT INTO `pays` (`id`, `nom`) values ('BW', 'Botswana');
  INSERT INTO `pays` (`id`, `nom`) values ('BR', 'Brésil');
  INSERT INTO `pays` (`id`, `nom`) values ('BN', 'Brunéi Darussalam');
  INSERT INTO `pays` (`id`, `nom`) values ('BG', 'Bulgarie');
  INSERT INTO `pays` (`id`, `nom`) values ('BF', 'Burkina Faso');
  INSERT INTO `pays` (`id`, `nom`) values ('BI', 'Burundi');
  INSERT INTO `pays` (`id`, `nom`) values ('KH', 'Cambodge');
  INSERT INTO `pays` (`id`, `nom`) values ('CM', 'Cameroun');
  INSERT INTO `pays` (`id`, `nom`) values ('CA', 'Canada');
  INSERT INTO `pays` (`id`, `nom`) values ('CV', 'Cap-Vert');
  INSERT INTO `pays` (`id`, `nom`) values ('EA', 'Ceuta et Melilla');
  INSERT INTO `pays` (`id`, `nom`) values ('CL', 'Chili');
  INSERT INTO `pays` (`id`, `nom`) values ('CN', 'Chine');
  INSERT INTO `pays` (`id`, `nom`) values ('CY', 'Chypre');
  INSERT INTO `pays` (`id`, `nom`) values ('CO', 'Colombie');
  INSERT INTO `pays` (`id`, `nom`) values ('KM', 'Comores');
  INSERT INTO `pays` (`id`, `nom`) values ('CG', 'Congo-Brazzaville');
  INSERT INTO `pays` (`id`, `nom`) values ('CD', 'Congo-Kinshasa');
  INSERT INTO `pays` (`id`, `nom`) values ('KP', 'Corée du Nord');
  INSERT INTO `pays` (`id`, `nom`) values ('KR', 'Corée du Sud');
  INSERT INTO `pays` (`id`, `nom`) values ('CR', 'Costa Rica');
  INSERT INTO `pays` (`id`, `nom`) values ('CI', 'Côte d’Ivoire');
  INSERT INTO `pays` (`id`, `nom`) values ('HR', 'Croatie');
  INSERT INTO `pays` (`id`, `nom`) values ('CU', 'Cuba');
  INSERT INTO `pays` (`id`, `nom`) values ('CW', 'Curaçao');
  INSERT INTO `pays` (`id`, `nom`) values ('DK', 'Danemark');
  INSERT INTO `pays` (`id`, `nom`) values ('DG', 'Diego Garcia');
  INSERT INTO `pays` (`id`, `nom`) values ('DJ', 'Djibouti');
  INSERT INTO `pays` (`id`, `nom`) values ('DM', 'Dominique');
  INSERT INTO `pays` (`id`, `nom`) values ('EG', 'Égypte');
  INSERT INTO `pays` (`id`, `nom`) values ('SV', 'El Salvador');
  INSERT INTO `pays` (`id`, `nom`) values ('AE', 'Émirats arabes unis');
  INSERT INTO `pays` (`id`, `nom`) values ('EC', 'Équateur');
  INSERT INTO `pays` (`id`, `nom`) values ('ER', 'Érythrée');
  INSERT INTO `pays` (`id`, `nom`) values ('ES', 'Espagne');
  INSERT INTO `pays` (`id`, `nom`) values ('EE', 'Estonie');
  INSERT INTO `pays` (`id`, `nom`) values ('VA', 'État de la Cité du Vatican');
  INSERT INTO `pays` (`id`, `nom`) values ('FM', 'États fédérés de Micronésie');
  INSERT INTO `pays` (`id`, `nom`) values ('US', 'États-Unis');
  INSERT INTO `pays` (`id`, `nom`) values ('ET', 'Éthiopie');
  INSERT INTO `pays` (`id`, `nom`) values ('FJ', 'Fidji');
  INSERT INTO `pays` (`id`, `nom`) values ('FI', 'Finlande');
  INSERT INTO `pays` (`id`, `nom`) values ('FR', 'France');
  INSERT INTO `pays` (`id`, `nom`) values ('GA', 'Gabon');
  INSERT INTO `pays` (`id`, `nom`) values ('GM', 'Gambie');
  INSERT INTO `pays` (`id`, `nom`) values ('GE', 'Géorgie');
  INSERT INTO `pays` (`id`, `nom`) values ('GH', 'Ghana');
  INSERT INTO `pays` (`id`, `nom`) values ('GI', 'Gibraltar');
  INSERT INTO `pays` (`id`, `nom`) values ('GR', 'Grèce');
  INSERT INTO `pays` (`id`, `nom`) values ('GD', 'Grenade');
  INSERT INTO `pays` (`id`, `nom`) values ('GL', 'Groenland');
  INSERT INTO `pays` (`id`, `nom`) values ('GP', 'Guadeloupe');
  INSERT INTO `pays` (`id`, `nom`) values ('GU', 'Guam');
  INSERT INTO `pays` (`id`, `nom`) values ('GT', 'Guatemala');
  INSERT INTO `pays` (`id`, `nom`) values ('GG', 'Guernesey');
  INSERT INTO `pays` (`id`, `nom`) values ('GN', 'Guinée');
  INSERT INTO `pays` (`id`, `nom`) values ('GQ', 'Guinée équatoriale');
  INSERT INTO `pays` (`id`, `nom`) values ('GW', 'Guinée-Bissau');
  INSERT INTO `pays` (`id`, `nom`) values ('GY', 'Guyana');
  INSERT INTO `pays` (`id`, `nom`) values ('GF', 'Guyane française');
  INSERT INTO `pays` (`id`, `nom`) values ('HT', 'Haïti');
  INSERT INTO `pays` (`id`, `nom`) values ('HN', 'Honduras');
  INSERT INTO `pays` (`id`, `nom`) values ('HU', 'Hongrie');
  INSERT INTO `pays` (`id`, `nom`) values ('CX', 'Île Christmas');
  INSERT INTO `pays` (`id`, `nom`) values ('AC', 'Île de l’Ascension');
  INSERT INTO `pays` (`id`, `nom`) values ('IM', 'Île de Man');
  INSERT INTO `pays` (`id`, `nom`) values ('NF', 'Île Norfolk');
  INSERT INTO `pays` (`id`, `nom`) values ('AX', 'Îles Åland');
  INSERT INTO `pays` (`id`, `nom`) values ('KY', 'Îles Caïmans');
  INSERT INTO `pays` (`id`, `nom`) values ('IC', 'Îles Canaries');
  INSERT INTO `pays` (`id`, `nom`) values ('CC', 'Îles Cocos');
  INSERT INTO `pays` (`id`, `nom`) values ('CK', 'Îles Cook');
  INSERT INTO `pays` (`id`, `nom`) values ('FO', 'Îles Féroé');
  INSERT INTO `pays` (`id`, `nom`) values ('GS', 'Îles Géorgie du Sud et Sandwich du Sud');
  INSERT INTO `pays` (`id`, `nom`) values ('FK', 'Îles Malouines');
  INSERT INTO `pays` (`id`, `nom`) values ('MP', 'Îles Mariannes du Nord');
  INSERT INTO `pays` (`id`, `nom`) values ('MH', 'Îles Marshall');
  INSERT INTO `pays` (`id`, `nom`) values ('UM', 'Îles mineures éloignées des États-Unis');
  INSERT INTO `pays` (`id`, `nom`) values ('SB', 'Îles Salomon');
  INSERT INTO `pays` (`id`, `nom`) values ('TC', 'Îles Turques-et-Caïques');
  INSERT INTO `pays` (`id`, `nom`) values ('VG', 'Îles Vierges britanniques');
  INSERT INTO `pays` (`id`, `nom`) values ('VI', 'Îles Vierges des États-Unis');
  INSERT INTO `pays` (`id`, `nom`) values ('IN', 'Inde');
  INSERT INTO `pays` (`id`, `nom`) values ('ID', 'Indonésie');
  INSERT INTO `pays` (`id`, `nom`) values ('IQ', 'Irak');
  INSERT INTO `pays` (`id`, `nom`) values ('IR', 'Iran');
  INSERT INTO `pays` (`id`, `nom`) values ('IE', 'Irlande');
  INSERT INTO `pays` (`id`, `nom`) values ('IS', 'Islande');
  INSERT INTO `pays` (`id`, `nom`) values ('IL', 'Israël');
  INSERT INTO `pays` (`id`, `nom`) values ('IT', 'Italie');
  INSERT INTO `pays` (`id`, `nom`) values ('JM', 'Jamaïque');
  INSERT INTO `pays` (`id`, `nom`) values ('JP', 'Japon');
  INSERT INTO `pays` (`id`, `nom`) values ('JE', 'Jersey');
  INSERT INTO `pays` (`id`, `nom`) values ('JO', 'Jordanie');
  INSERT INTO `pays` (`id`, `nom`) values ('KZ', 'Kazakhstan');
  INSERT INTO `pays` (`id`, `nom`) values ('KE', 'Kenya');
  INSERT INTO `pays` (`id`, `nom`) values ('KG', 'Kirghizistan');
  INSERT INTO `pays` (`id`, `nom`) values ('KI', 'Kiribati');
  INSERT INTO `pays` (`id`, `nom`) values ('XK', 'Kosovo');
  INSERT INTO `pays` (`id`, `nom`) values ('KW', 'Koweït');
  INSERT INTO `pays` (`id`, `nom`) values ('RE', 'La Réunion');
  INSERT INTO `pays` (`id`, `nom`) values ('LA', 'Laos');
  INSERT INTO `pays` (`id`, `nom`) values ('LS', 'Lesotho');
  INSERT INTO `pays` (`id`, `nom`) values ('LV', 'Lettonie');
  INSERT INTO `pays` (`id`, `nom`) values ('LB', 'Liban');
  INSERT INTO `pays` (`id`, `nom`) values ('LR', 'Libéria');
  INSERT INTO `pays` (`id`, `nom`) values ('LY', 'Libye');
  INSERT INTO `pays` (`id`, `nom`) values ('LI', 'Liechtenstein');
  INSERT INTO `pays` (`id`, `nom`) values ('LT', 'Lituanie');
  INSERT INTO `pays` (`id`, `nom`) values ('LU', 'Luxembourg');
  INSERT INTO `pays` (`id`, `nom`) values ('MK', 'Macédoine');
  INSERT INTO `pays` (`id`, `nom`) values ('MG', 'Madagascar');
  INSERT INTO `pays` (`id`, `nom`) values ('MY', 'Malaisie');
  INSERT INTO `pays` (`id`, `nom`) values ('MW', 'Malawi');
  INSERT INTO `pays` (`id`, `nom`) values ('MV', 'Maldives');
  INSERT INTO `pays` (`id`, `nom`) values ('ML', 'Mali');
  INSERT INTO `pays` (`id`, `nom`) values ('MT', 'Malte');
  INSERT INTO `pays` (`id`, `nom`) values ('MA', 'Maroc');
  INSERT INTO `pays` (`id`, `nom`) values ('MQ', 'Martinique');
  INSERT INTO `pays` (`id`, `nom`) values ('MU', 'Maurice');
  INSERT INTO `pays` (`id`, `nom`) values ('MR', 'Mauritanie');
  INSERT INTO `pays` (`id`, `nom`) values ('YT', 'Mayotte');
  INSERT INTO `pays` (`id`, `nom`) values ('MX', 'Mexique');
  INSERT INTO `pays` (`id`, `nom`) values ('MD', 'Moldavie');
  INSERT INTO `pays` (`id`, `nom`) values ('MC', 'Monaco');
  INSERT INTO `pays` (`id`, `nom`) values ('MN', 'Mongolie');
  INSERT INTO `pays` (`id`, `nom`) values ('ME', 'Monténégro');
  INSERT INTO `pays` (`id`, `nom`) values ('MS', 'Montserrat');
  INSERT INTO `pays` (`id`, `nom`) values ('MZ', 'Mozambique');
  INSERT INTO `pays` (`id`, `nom`) values ('MM', 'Myanmar');
  INSERT INTO `pays` (`id`, `nom`) values ('NA', 'Namibie');
  INSERT INTO `pays` (`id`, `nom`) values ('NR', 'Nauru');
  INSERT INTO `pays` (`id`, `nom`) values ('NP', 'Népal');
  INSERT INTO `pays` (`id`, `nom`) values ('NI', 'Nicaragua');
  INSERT INTO `pays` (`id`, `nom`) values ('NE', 'Niger');
  INSERT INTO `pays` (`id`, `nom`) values ('NG', 'Nigéria');
  INSERT INTO `pays` (`id`, `nom`) values ('NU', 'Niue');
  INSERT INTO `pays` (`id`, `nom`) values ('NO', 'Norvège');
  INSERT INTO `pays` (`id`, `nom`) values ('NC', 'Nouvelle-Calédonie');
  INSERT INTO `pays` (`id`, `nom`) values ('NZ', 'Nouvelle-Zélande');
  INSERT INTO `pays` (`id`, `nom`) values ('OM', 'Oman');
  INSERT INTO `pays` (`id`, `nom`) values ('UG', 'Ouganda');
  INSERT INTO `pays` (`id`, `nom`) values ('UZ', 'Ouzbékistan');
  INSERT INTO `pays` (`id`, `nom`) values ('PK', 'Pakistan');
  INSERT INTO `pays` (`id`, `nom`) values ('PW', 'Palaos');
  INSERT INTO `pays` (`id`, `nom`) values ('PA', 'Panama');
  INSERT INTO `pays` (`id`, `nom`) values ('PG', 'Papouasie-Nouvelle-Guinée');
  INSERT INTO `pays` (`id`, `nom`) values ('PY', 'Paraguay');
  INSERT INTO `pays` (`id`, `nom`) values ('NL', 'Pays-Bas');
  INSERT INTO `pays` (`id`, `nom`) values ('BQ', 'Pays-Bas caribéens');
  INSERT INTO `pays` (`id`, `nom`) values ('PE', 'Pérou');
  INSERT INTO `pays` (`id`, `nom`) values ('PH', 'Philippines');
  INSERT INTO `pays` (`id`, `nom`) values ('PN', 'Pitcairn');
  INSERT INTO `pays` (`id`, `nom`) values ('PL', 'Pologne');
  INSERT INTO `pays` (`id`, `nom`) values ('PF', 'Polynésie française');
  INSERT INTO `pays` (`id`, `nom`) values ('PR', 'Porto Rico');
  INSERT INTO `pays` (`id`, `nom`) values ('PT', 'Portugal');
  INSERT INTO `pays` (`id`, `nom`) values ('QA', 'Qatar');
  INSERT INTO `pays` (`id`, `nom`) values ('HK', 'R.A.S. chinoise de Hong Kong');
  INSERT INTO `pays` (`id`, `nom`) values ('MO', 'R.A.S. chinoise de Macao');
  INSERT INTO `pays` (`id`, `nom`) values ('CF', 'République centrafricaine');
  INSERT INTO `pays` (`id`, `nom`) values ('DO', 'République dominicaine');
  INSERT INTO `pays` (`id`, `nom`) values ('CZ', 'République tchèque');
  INSERT INTO `pays` (`id`, `nom`) values ('RO', 'Roumanie');
  INSERT INTO `pays` (`id`, `nom`) values ('GB', 'Royaume-Uni');
  INSERT INTO `pays` (`id`, `nom`) values ('RU', 'Russie');
  INSERT INTO `pays` (`id`, `nom`) values ('RW', 'Rwanda');
  INSERT INTO `pays` (`id`, `nom`) values ('EH', 'Sahara occidental');
  INSERT INTO `pays` (`id`, `nom`) values ('BL', 'Saint-Barthélemy');
  INSERT INTO `pays` (`id`, `nom`) values ('KN', 'Saint-Christophe-et-Niévès');
  INSERT INTO `pays` (`id`, `nom`) values ('SM', 'Saint-Marin');
  INSERT INTO `pays` (`id`, `nom`) values ('MF', 'Saint-Martin (partie française)');
  INSERT INTO `pays` (`id`, `nom`) values ('SX', 'Saint-Martin (partie néerlandaise)');
  INSERT INTO `pays` (`id`, `nom`) values ('PM', 'Saint-Pierre-et-Miquelon');
  INSERT INTO `pays` (`id`, `nom`) values ('VC', 'Saint-Vincent-et-les-Grenadines');
  INSERT INTO `pays` (`id`, `nom`) values ('SH', 'Sainte-Hélène');
  INSERT INTO `pays` (`id`, `nom`) values ('LC', 'Sainte-Lucie');
  INSERT INTO `pays` (`id`, `nom`) values ('WS', 'Samoa');
  INSERT INTO `pays` (`id`, `nom`) values ('AS', 'Samoa américaines');
  INSERT INTO `pays` (`id`, `nom`) values ('ST', 'Sao Tomé-et-Principe');
  INSERT INTO `pays` (`id`, `nom`) values ('SN', 'Sénégal');
  INSERT INTO `pays` (`id`, `nom`) values ('RS', 'Serbie');
  INSERT INTO `pays` (`id`, `nom`) values ('SC', 'Seychelles');
  INSERT INTO `pays` (`id`, `nom`) values ('SL', 'Sierra Leone');
  INSERT INTO `pays` (`id`, `nom`) values ('SG', 'Singapour');
  INSERT INTO `pays` (`id`, `nom`) values ('SK', 'Slovaquie');
  INSERT INTO `pays` (`id`, `nom`) values ('SI', 'Slovénie');
  INSERT INTO `pays` (`id`, `nom`) values ('SO', 'Somalie');
  INSERT INTO `pays` (`id`, `nom`) values ('SD', 'Soudan');
  INSERT INTO `pays` (`id`, `nom`) values ('SS', 'Soudan du Sud');
  INSERT INTO `pays` (`id`, `nom`) values ('LK', 'Sri Lanka');
  INSERT INTO `pays` (`id`, `nom`) values ('SE', 'Suède');
  INSERT INTO `pays` (`id`, `nom`) values ('CH', 'Suisse');
  INSERT INTO `pays` (`id`, `nom`) values ('SR', 'Suriname');
  INSERT INTO `pays` (`id`, `nom`) values ('SJ', 'Svalbard et Jan Mayen');
  INSERT INTO `pays` (`id`, `nom`) values ('SZ', 'Swaziland');
  INSERT INTO `pays` (`id`, `nom`) values ('SY', 'Syrie');
  INSERT INTO `pays` (`id`, `nom`) values ('TJ', 'Tadjikistan');
  INSERT INTO `pays` (`id`, `nom`) values ('TW', 'Taïwan');
  INSERT INTO `pays` (`id`, `nom`) values ('TZ', 'Tanzanie');
  INSERT INTO `pays` (`id`, `nom`) values ('TD', 'Tchad');
  INSERT INTO `pays` (`id`, `nom`) values ('TF', 'Terres australes françaises');
  INSERT INTO `pays` (`id`, `nom`) values ('IO', 'Territoire britannique de l’océan Indien');
  INSERT INTO `pays` (`id`, `nom`) values ('PS', 'Territoires palestiniens');
  INSERT INTO `pays` (`id`, `nom`) values ('TH', 'Thaïlande');
  INSERT INTO `pays` (`id`, `nom`) values ('TL', 'Timor oriental');
  INSERT INTO `pays` (`id`, `nom`) values ('TG', 'Togo');
  INSERT INTO `pays` (`id`, `nom`) values ('TK', 'Tokelau');
  INSERT INTO `pays` (`id`, `nom`) values ('TO', 'Tonga');
  INSERT INTO `pays` (`id`, `nom`) values ('TT', 'Trinité-et-Tobago');
  INSERT INTO `pays` (`id`, `nom`) values ('TA', 'Tristan da Cunha');
  INSERT INTO `pays` (`id`, `nom`) values ('TN', 'Tunisie');
  INSERT INTO `pays` (`id`, `nom`) values ('TM', 'Turkménistan');
  INSERT INTO `pays` (`id`, `nom`) values ('TR', 'Turquie');
  INSERT INTO `pays` (`id`, `nom`) values ('TV', 'Tuvalu');
  INSERT INTO `pays` (`id`, `nom`) values ('UA', 'Ukraine');
  INSERT INTO `pays` (`id`, `nom`) values ('UY', 'Uruguay');
  INSERT INTO `pays` (`id`, `nom`) values ('VU', 'Vanuatu');
  INSERT INTO `pays` (`id`, `nom`) values ('VE', 'Venezuela');
  INSERT INTO `pays` (`id`, `nom`) values ('VN', 'Vietnam');
  INSERT INTO `pays` (`id`, `nom`) values ('WF', 'Wallis-et-Futuna');
  INSERT INTO `pays` (`id`, `nom`) values ('YE', 'Yémen');
  INSERT INTO `pays` (`id`, `nom`) values ('ZM', 'Zambie');
  INSERT INTO `pays` (`id`, `nom`) values ('ZW', 'Zimbabwe');
